---
title: "MQU Birdata  2025 Taxonomy Matching"
author: "Michael Dear"
date: "2025-07-07"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
This project aims to match the Birdata (BD) taxonomy to the Atlas of Living Australia (ALA) taxonomy. The scope is all bird species identified in either BD or ALA for the given study area. The overall goal is to produce a dataset in which BD data is incorporated into the ALA data using ALA scientific and common names.

## Method
An iterative approach is taken to matching. Exact matches on either scientific name or common name are resolved first. The residual records are matched using approximate matching techniques. BD is taken as the source and is matched against ALA. A translation table is produced in which BD names are matched against ALA names. The translation table is tested on a subset of BD data and reviewed for accuracy.

# Setup

# Data Preparation

# Match Taxonomies

# Accuracy Assessment